# Generated by Django 5.0.5 on 2024-06-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='publicationDate',
            field=models.DateField(auto_now=True),
        ),
    ]
